import { OrganizationModel } from "../models";

export let organizations: OrganizationModel[] = [
  {
    id: "org-1",
    name: "ReHouser",
    registrationNumber: "12345-67890",
    address: "5 Monowai road",
    city: "Dunedin",
    state: "NY",
    postalCode: "9052",
    country: "New Zealand",
    phoneNumber: "+1 (123) 456-7890",
    email: "heath.dunlop.hd@gmail.com",
    website: "https://www.abccorp.com",
    foundingDate: "2023-08-15",
    industry: "Technology",
    description: "A technology company",
  },
  {
    id: "org-2",
    name: "ABC Corporation",
    registrationNumber: "12345-67890",
    address: "123 Main Street",
    city: "New York",
    state: "NY",
    postalCode: "10001",
    country: "United States",
    phoneNumber: "+1 (123) 456-7890",
    email: "contact@abccorp.com",
    website: "https://www.abccorp.com",
    foundingDate: "2005-08-15",
    industry: "Technology",
    description:
      "ABC Corporation is a leading technology company specializing in software development and IT services.",
  },
  {
    id: "org-3",
    name: "XYZ Enterprises",
    registrationNumber: "98765-43210",
    address: "456 Elm Street",
    city: "Los Angeles",
    state: "CA",
    postalCode: "90001",
    country: "United States",
    phoneNumber: "+1 (555) 123-4567",
    email: "info@xyzenterprises.com",
    website: "https://www.xyzenterprises.com",
    foundingDate: "1990-04-20",
    industry: "Finance",
    description:
      "XYZ Enterprises is a financial services firm providing investment and wealth management solutions.",
  },
  {
    id: "org-4",
    name: "Global Innovations Ltd",
    registrationNumber: "54321-98765",
    address: "789 Oak Avenue",
    city: "London",
    state: "England",
    postalCode: "SW1A 1AA",
    country: "United Kingdom",
    phoneNumber: "+44 (0)20 1234 5678",
    email: "info@globalinnovations.co.uk",
    website: "https://www.globalinnovations.co.uk",
    foundingDate: "1990-04-20",
    industry: "Research and Development",
    description:
      "Global Innovations Ltd is a research and development company focused on cutting-edge technology solutions.",
  },
];
